### PR TITLE
Reduce force power off from 12s to 4s

### PR DESCRIPTION
**Pull request by CTCaer**
Useful when using mass storage features frequently.

It's possible to make that behavior better by adding it to ini though. And reduce the delay by case. Not included in this pr though.

Edit
Want me to make it case by case by ini config?

### CODE REVIEW

**Comment by rajkosto** [comment]
Does this register control anything else ?

**Comment by CTCaer** [comment]
**bit0**: Unknown
**bit1**: Instant power off
**bit2**: Sleep enable
**bit3:4 (if bit2 is enabled)**: POR reset on wake up
**bit3:5**: Delay for forced power off by pressing PWR btn.
**bit6**: Unknown. Enabled for HOS.
**bit7**: Restart (need to also config ONOFFCNFG2)

**Comment by rajkosto** [comment]
Table for delays ? Since 0x48 has it as "1" by that structure

**Comment by CTCaer** [comment]
x8 is 1.
From testing done not by me, 0 is 2s, 1 is 4s, 2 is 6s and so on.

EDIT: Wait gonna find this test
EDIT2:
Courtesy of @langerhans
```
0 = 2s
1 = 4s
2 = 4s
3 = 6s
4 = 6s
5 = 8s
6 = 10s
7 = 12s
```

They are not exact. But good enough. ¯\_(ツ)_/¯

**Comment by CTCaer** [comment]
here's the correct:
```
mrt_time = (mrt_time > 12) ? 12 : mrt_time; 
if (mrt_time <= 6) 
    reg_val = mrt_time - 2; 
else 
    reg_val = (mrt_time - 6) / 2 + 4; 
```

**Comment by rajkosto** [comment]
Don't know if the ini option should have the value in seconds or just directly in their units from 0-7 (since the range is pretty low and imprecise either way)

**Comment by CTCaer** [comment]
It's better in units. Less code to acquire them and use them, imo

**Comment by rajkosto** [comment]
Implemented properly in https://github.com/rajkosto/memloader/commit/13025fa87b60e9027c59aaacf5606a4a509b640d

**Pull request closed without merging**
